version: '3'
services:
  database:
    container_name: database-insys
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./docker/db_volume/:/var/lib/postgresql/data

volumes:
  mysqldata: