# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobs import game_protoc_pb2 as protobs_dot_game__protoc__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobs/game_protoc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserAuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/game.UserAuth/Register',
                request_serializer=protobs_dot_game__protoc__pb2.RegisterRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/game.UserAuth/Login',
                request_serializer=protobs_dot_game__protoc__pb2.LoginRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.Loginresponse.FromString,
                _registered_method=True)
        self.Me = channel.unary_unary(
                '/game.UserAuth/Me',
                request_serializer=protobs_dot_game__protoc__pb2.MeRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.MeResponse.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/game.UserAuth/UpdatePassword',
                request_serializer=protobs_dot_game__protoc__pb2.UpdatePasswordRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.UpdatePasswordResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/game.UserAuth/DeleteUser',
                request_serializer=protobs_dot_game__protoc__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.DeleteUserResponse.FromString,
                _registered_method=True)


class UserAuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Me(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=protobs_dot_game__protoc__pb2.RegisterRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protobs_dot_game__protoc__pb2.LoginRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.Loginresponse.SerializeToString,
            ),
            'Me': grpc.unary_unary_rpc_method_handler(
                    servicer.Me,
                    request_deserializer=protobs_dot_game__protoc__pb2.MeRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.MeResponse.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=protobs_dot_game__protoc__pb2.UpdatePasswordRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.UpdatePasswordResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=protobs_dot_game__protoc__pb2.DeleteUserRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.UserAuth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserAuth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.UserAuth/Register',
            protobs_dot_game__protoc__pb2.RegisterRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.UserAuth/Login',
            protobs_dot_game__protoc__pb2.LoginRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.Loginresponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Me(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.UserAuth/Me',
            protobs_dot_game__protoc__pb2.MeRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.MeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.UserAuth/UpdatePassword',
            protobs_dot_game__protoc__pb2.UpdatePasswordRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.UpdatePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.UserAuth/DeleteUser',
            protobs_dot_game__protoc__pb2.DeleteUserRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GameUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserDetail = channel.unary_unary(
                '/game.GameUser/GetUserDetail',
                request_serializer=protobs_dot_game__protoc__pb2.UserDetailRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.UserDetailResponse.FromString,
                _registered_method=True)
        self.GetRecentGame = channel.unary_unary(
                '/game.GameUser/GetRecentGame',
                request_serializer=protobs_dot_game__protoc__pb2.RecentGameRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.RecentGameResponse.FromString,
                _registered_method=True)
        self.GetLeaderBoard = channel.unary_unary(
                '/game.GameUser/GetLeaderBoard',
                request_serializer=protobs_dot_game__protoc__pb2.LeaderboardRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.LeaderboardResponse.FromString,
                _registered_method=True)


class GameUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaderBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDetail,
                    request_deserializer=protobs_dot_game__protoc__pb2.UserDetailRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.UserDetailResponse.SerializeToString,
            ),
            'GetRecentGame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentGame,
                    request_deserializer=protobs_dot_game__protoc__pb2.RecentGameRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.RecentGameResponse.SerializeToString,
            ),
            'GetLeaderBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaderBoard,
                    request_deserializer=protobs_dot_game__protoc__pb2.LeaderboardRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.LeaderboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameUser/GetUserDetail',
            protobs_dot_game__protoc__pb2.UserDetailRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.UserDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameUser/GetRecentGame',
            protobs_dot_game__protoc__pb2.RecentGameRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.RecentGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeaderBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameUser/GetLeaderBoard',
            protobs_dot_game__protoc__pb2.LeaderboardRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.LeaderboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GameGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetgameDetail = channel.unary_unary(
                '/game.GameGame/GetgameDetail',
                request_serializer=protobs_dot_game__protoc__pb2.GameDetailRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.GameDetailResponse.FromString,
                _registered_method=True)
        self.CreateGame = channel.unary_unary(
                '/game.GameGame/CreateGame',
                request_serializer=protobs_dot_game__protoc__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.CreateGameResponse.FromString,
                _registered_method=True)
        self.UpdateMove = channel.unary_unary(
                '/game.GameGame/UpdateMove',
                request_serializer=protobs_dot_game__protoc__pb2.UpdateMoveRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.UpdateMoveResponse.FromString,
                _registered_method=True)
        self.EndGame = channel.unary_unary(
                '/game.GameGame/EndGame',
                request_serializer=protobs_dot_game__protoc__pb2.EndGameRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.EndGameResponse.FromString,
                _registered_method=True)
        self.GetBotMove = channel.unary_unary(
                '/game.GameGame/GetBotMove',
                request_serializer=protobs_dot_game__protoc__pb2.BotMoveRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.BotMoveResponse.FromString,
                _registered_method=True)


class GameGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetgameDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBotMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetgameDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetgameDetail,
                    request_deserializer=protobs_dot_game__protoc__pb2.GameDetailRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.GameDetailResponse.SerializeToString,
            ),
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=protobs_dot_game__protoc__pb2.CreateGameRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.CreateGameResponse.SerializeToString,
            ),
            'UpdateMove': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMove,
                    request_deserializer=protobs_dot_game__protoc__pb2.UpdateMoveRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.UpdateMoveResponse.SerializeToString,
            ),
            'EndGame': grpc.unary_unary_rpc_method_handler(
                    servicer.EndGame,
                    request_deserializer=protobs_dot_game__protoc__pb2.EndGameRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.EndGameResponse.SerializeToString,
            ),
            'GetBotMove': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotMove,
                    request_deserializer=protobs_dot_game__protoc__pb2.BotMoveRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.BotMoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetgameDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameGame/GetgameDetail',
            protobs_dot_game__protoc__pb2.GameDetailRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.GameDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameGame/CreateGame',
            protobs_dot_game__protoc__pb2.CreateGameRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.CreateGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameGame/UpdateMove',
            protobs_dot_game__protoc__pb2.UpdateMoveRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.UpdateMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameGame/EndGame',
            protobs_dot_game__protoc__pb2.EndGameRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.EndGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBotMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameGame/GetBotMove',
            protobs_dot_game__protoc__pb2.BotMoveRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.BotMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GameRoomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
                '/game.GameRoom/CreateRoom',
                request_serializer=protobs_dot_game__protoc__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.CreateRoomResponse.FromString,
                _registered_method=True)
        self.JoinRoom = channel.unary_unary(
                '/game.GameRoom/JoinRoom',
                request_serializer=protobs_dot_game__protoc__pb2.JoinRoomRequest.SerializeToString,
                response_deserializer=protobs_dot_game__protoc__pb2.JoinroomResponse.FromString,
                _registered_method=True)


class GameRoomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameRoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=protobs_dot_game__protoc__pb2.CreateRoomRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.CreateRoomResponse.SerializeToString,
            ),
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=protobs_dot_game__protoc__pb2.JoinRoomRequest.FromString,
                    response_serializer=protobs_dot_game__protoc__pb2.JoinroomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameRoom', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameRoom(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameRoom/CreateRoom',
            protobs_dot_game__protoc__pb2.CreateRoomRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameRoom/JoinRoom',
            protobs_dot_game__protoc__pb2.JoinRoomRequest.SerializeToString,
            protobs_dot_game__protoc__pb2.JoinroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
